### ISSUE TITLE
Error: spawn mongodb://localhost/test ENOENT

### ISSUE THREAD

**Issue by farhantahir** [supercharge/mongodb-github-action#15]
Facing following error with this.

```Error: spawn mongodb://localhost/test ENOENT```

what could be wrong here.

```
- name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
```
