### ISSUE TITLE
MongoDB 4.4 support

### ISSUE THREAD

**Issue by gimperiale** [supercharge/mongodb-github-action#17]
MongoDB 4.4 was released on July 2020.
Could we add support here?

**Comment by marcuspoehls** [comment]
@gimperiale Hey, MongoDB 4.4 is already supported. This GitHub Action uses the specified MongoDB version and searches for an available Docker container in the Docker hub.

This should already work for you without any changes in this package:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2, 4.4]
```

Can you try it?
