### ISSUE TITLE
Connection timeout 

### ISSUE THREAD

**Issue by jorgeluisrezende** [supercharge/mongodb-github-action#30]
I've trying to use this action, but my application are not connecting on mongo db, Im receving a timeout error.

```
|     MongoServerSelectionError: connection timed out
|         at Timeout._onTimeout (/home/jorge/Projetos/gira-serve/node_modules/parse-server/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
|         at listOnTimeout (internal/timers.js:557:17)
|         at processTimers (internal/timers.js:500:7) {
|       reason: TopologyDescription {
|         type: 'Single',
|         setName: null,
|         maxSetVersion: null,
|         maxElectionId: null,
|         servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
|         stale: false,
|         compatible: true,
|         compatibilityError: null,
|         logicalSessionTimeoutMinutes: null,
|         heartbeatFrequencyMS: 10000,
|         localThresholdMS: 15,
|         commonWireVersion: null
|       }
|     }
```

```yml
 integration-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
                mongodb-version: ['4.4']
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                node-version: 14

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                mongodb-version: 4.4
                mongodb-db: test-database

            - run: npm install -g yarn
            - run: yarn install
            - run: yarn test:integration
              env:
                NODE_ENV: test
                PARSE_SERVER_DATABASE_URI: mongodb://127.0.0.1:27017/test-database?directConnection=true
                DATABASE_NAME: test-database
```

**Comment by marcuspoehls** [comment]
@jorgeluisrezende Hey Jorge, can you please share your Node.js code that connects to MongoDB? I’m thinking of connection options could be wrong

**Comment by jorgeluisrezende** [comment]
@marcuspoehls Im using [ParseServer](https://docs.parseplatform.org/) so I'm doing exactly as written in documentation, just instantiating a new ParseServer like..
```js
        this.parseServer = new ParseServer({
            databaseURI: process.env.PARSE_SERVER_DATABASE_URI,
            ...myconfigs,
        });
```

**Comment by marcuspoehls** [comment]
@jorgeluisrezende Your connection config looks fine. I can’t tell what your issue is. I remember having connection issues in the past related to server selection timeout errors too. Not sure how I solved them. Maybe you can find details about MongoDB starting properly in your GitHub Actions steps. The logs of each step may show you if something is off

**Comment by marcuspoehls** [comment]
@jorgeluisrezende Hey Jorge, have you been able to fix the issue?

**Comment by jorgeluisrezende** [comment]
@marcuspoehls no, I've tested a lot of configs but my workflow still crashing when it tries to connect on mongo, I think its a bug on github runner, i will test it on my own runner to see if it will pass

**Comment by jorgeluisrezende** [comment]
Thank you for the help!!

**Comment by jorgeluisrezende** [comment]
I've tried with both, running inside a container and inside a vm directly, and all tests failed, I even tried to get the container ip and connect on it but again it failed

**Comment by marcuspoehls** [comment]
OK, thank you for sharing your tries.

**Comment by aprilahijriyan** [comment]
Hi, I'm experiencing the same thing. Is there any way to fix it?

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/37798612/178312063-e43aa239-94e2-4229-84f2-41f075ef467c.png">

Workflow:

```yaml
name: Unit testing

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  test_job:
    name: Run tests using python v${{ matrix.py }}
    runs-on: ubuntu-latest
    environment: getpay-api
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.9"
          - "3.8"

    steps:
      - uses: actions/checkout@v3
      - name: Setup python v${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Create environment file
        run: printf '${{secrets.ENV_FILE}}' >> .env

      - name: Export environment variables (app .env)
        uses: cardinalby/export-env-action@1.0.0
        with:
          envFile: .env

      - name: Export environment variables (testing .env)
        uses: cardinalby/export-env-action@1.0.0
        with:
          envFile: .env.testing

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: latest

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
          mongodb-username: ${{env.MONGODB_USERNAME}}
          mongodb-password: ${{env.MONGO_PASSWORD}}
          mongodb-db: ${{env.MONGODB_DATABASE}}

      - name: Install dependencies
        run: |
          pip install -r all-requirements.txt

      - name: Initialize data
        run: |
          python3 manage.py init
          python3 manage.py create_user -u ${{env.USER_EMAIL}} -p ${{env.USER_PASSWORD}} -y

      - name: Run tests
        run: |
          pytest -v --cache-clear

```

The error appears in step ``Initialize data``.
