### ISSUE TITLE
How to restart mongo after adding users?

### ISSUE THREAD

**Issue by vnugent** [supercharge/mongodb-github-action#32]
I know we can't specify initial user **and** use replicaset at the same time.   After adding a test user, how do we restart mongo with --auth mode enabled?

```
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5
          mongodb-replica-set: rs0

      - name: Wait for the database to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:27017 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
      
      - name: Setup test user
        run: |
           source .env && \
           mongo admin --eval "db.createUser({user: '${MONGO_INITDB_ROOT_USERNAME}', pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: ['readWrite']})"

    # how to start mongo with --auth enabled?
```
