### ISSUE TITLE
MongoServerError: Authentication failed.

### ISSUE THREAD

**Issue by tar-aldev** [supercharge/mongodb-github-action#54]
I am following the docs and I've set `MONGODB_USERNAME` and `MONGODB_PASSWORD` in github actions -> secrets.
yaml file for workflow looks like this
```
env:
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

setup-mongodb:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-username: ${{env.MONGODB_USERNAME}}
          mongodb-password: ${{env.MONGODB_PASSWORD}}
          mongodb-db: test
```

When running it I see
```
Starting single-node instance, no replica set
    - port [27017]
    - version [latest]
    - database [test]
    - credentials [***:***]
```

And then this
```
Waiting for MongoDB to accept connections
  ]0;mongosh mongodb://<credentials>@127.0.0.1:27017/?***&serverSelectionTimeoutMS=2000MongoServerError: Authentication failed.
```
Any idea what's going on?

**Comment by marcuspoehls** [comment]
@tar-aldev Hey Alex, that’s strange. Did you try to hard-code a value for `mongodb-username` and `mongodb-password` to ensure the values show up correctly in the logs? It’s possible that credentials injected from GitHub secrets are obfuscated in the logs of GitHub Actions (to not expose sensitive data)

```
env:
  MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}

setup-mongodb:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-username: hardcoded-value
          mongodb-password: your-password
          mongodb-db: test
```
