### ISSUE TITLE
Action fails due to docker: toomanyrequests

### ISSUE THREAD

**Issue by emarchak** [supercharge/mongodb-github-action#62]
We're using this step in our gh actions and it failed due to the following error. 

It looks like we're unauthenticated with docker when pulling the mongodb lib, and I can't see anything in this actions code/readme authenticating against docker. Plus we're only running a few actions a day (small company), so my assumption is that we hit a rate limit with a few other anonymous users.

Any thoughts on how to correct this?

```
Selecting correct MongoDB client
    - Using MongoDB client: [mongosh --quiet]
  
Starting MongoDB as single-node replica set
    - port [42069]
    - version [5.0]
    - replica set [rs0]
  
  Unable to find image 'mongo:5.0' locally
  5.0: Pulling from library/mongo
  docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
  See 'docker run --help'.
  Error starting MongoDB Docker container
  ```
  
  Our config is the following:
  
  ```
        # Step: Start MongoDB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "5.0"
          mongodb-port: 42069
          mongodb-replica-set: rs0
```

**Comment by marcuspoehls** [comment]
I remember that Docker allows you to increase your rate limit when using authenticated requests. You may need to log in to Docker from your GitHub Actions. I don’t know how to do that in GitHub Actions, though 😬 please search for details on that topic yourself. Hope you find something related to Docker rate limiting when using GitHub Actions

**Comment by BioCarmen** [comment]
Hello. Seems like Login into Docker from github actions won't help in this case becasue Container pull happens at the first step of the build before docker login.  https://docs.docker.com/docker-hub/download-rate-limit/#github-actions 
Can we allow username and password for docker in this actions?

**Comment by oliver-hohn** [comment]
Hello 👋 We have encountered the issue today (something seems to have happened where Github runners were being rate limited: https://github.com/actions/runner-images/issues/1445#issuecomment-2271654727). Thought I'd post our investigation and what we did in case it's useful to others.

We found that our Github Action runner (**hosted by Github**) had it's IP address rate limited by Dockerhub. Presumably because more than 100 pulls were made from that IP address within a 6 hour period: https://docs.docker.com/docker-hub/download-rate-limit/.
So I then forked this repo and added support for optional `docker-login` to be done before the MongoDB image is pulled, but, after more debugging, the rate limiting was happening **when Github Actions builds the Docker image for this action** (i.e. at the "Build supercharge/mongodb-github-action" step, which builds using the [Dockerfile](https://github.com/supercharge/mongodb-github-action/blob/5a87bd81f88e2a8b195f8b7b656f5cda1350815a/Dockerfile#L1)). Which makes it very difficult to run `docker login`, as this happens before any of the logic in our Github action workflow runs (@BioCarmen is this what you found as well?)

I think to address this long-term, and allow clients of this Github Action to setup `docker login` themselves, this Github Action would need to be switched to be a Javascript action (or any none Docker action). So that when it is pulled into Github workflows, there is no Docker build step to build the action itself (as those are subject to rate limits). Happy to help on this if that's useful!


In terms of addressing the issue in the short-term, we've opted to start the MongoDB docker container directly in our workflow:
```yaml
- name: Start MongoDB
  id: start-mongodb
  run: |
    # Start MongoDB in a Docker container
    CONTAINER_ID=$(docker run --rm -p=27017:27017 --detach mongo:7 --replSet=rs0 --port=27017)
    echo "DOCKER_CONTAINER_ID=$CONTAINER_ID" >> "$GITHUB_OUTPUT"

    # Wait for MongoDB to be ready
    sleep 5

# etc...

- name: Shutdown MongoDB
  if: ${{always() && steps.start-mongodb.outputs.DOCKER_CONTAINER_ID}}
  run: docker stop ${{steps.start-mongodb.outputs.DOCKER_CONTAINER_ID}} 
```

Replica sets and other config can then be setup using similar logic to what is in [`start-mongodb.sh`](https://github.com/supercharge/mongodb-github-action/blob/5a87bd81f88e2a8b195f8b7b656f5cda1350815a/start-mongodb.sh#L1) (using `docker exec`).
