### ISSUE TITLE
Authentication error 

### ISSUE THREAD

**Issue by RobertCzaja** [supercharge/mongodb-github-action#63]
I added `supercharge/mongodb-github-action@1.11.0` in my Spring project directory `.github/workflows/maven.yaml` like that:

```
...
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '6.0'
        mongodb-replica-set: test-rs
        mongodb-username: supercharge
        mongodb-password: secret
        mongodb-db: supercharge

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn clean install
      env:
        MONGO_DB_USER: supercharge
        MONGO_DB_PASSWORD: secret
        MONGO_DB_NAME: supercharge
 ... 
```
Also I added a integration test that testing connection to MongoDB which is configured in application.yaml like that 
```
spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@localhost:27017/${MONGO_DB_NAME}
```
On running pipeline I still got authentication error 

`
[964](https://github.com/RobertCzaja/it-offers/actions/runs/10495377908/job/29073678830#step:7:965)Error:   MongoDBConnectionITest.shouldCorrectlySaveDataToMongoDB:27 » UncategorizedMongoDb Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='supercharge', source='supercharge', *** mechanismProperties=<hidden>}`
 
Could you tell me what I'm doing wrong, how I can configure that Mongo user correctly?
