### ISSUE TITLE
Action fails when run via act, but ok in github

### ISSUE THREAD

**Issue by dhowe** [supercharge/mongodb-github-action#70]
```
Playwright Tests/test]   ✅  Success - Main Install Playwright Browsers [1m23.414296292s]
[Playwright Tests/test] ⭐ Run Main Start MongoDB
[Playwright Tests/test]   🐳  docker build -t act-supercharge-mongodb-github-action-1-12-0-dockeraction:latest --platform linux/amd64 /Users/dhowe/.cache/act/supercharge-mongodb-github-action@1.12.0
[Playwright Tests/test]   ❌  Failure - Main Start MongoDB [4.758423958s]
[Playwright Tests/test] failed to export image: NotFound: content digest sha256:59a833fde12d7bcc06ff52f0b44a410d8000b7f132fd102db60c4454e3038bf5: not found
[Playwright Tests/test] ⭐ Run Main actions/upload-artifact@v4
[Playwright Tests/test]   🐳  docker cp src=/Users/dhowe/.cache/act/actions-upload-artifact@v4/ dst=/var/run/act/actions/actions-upload-artifact@v4/
[Playwright Tests/test]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.8/x64/bin/node /var/run/act/actions/actions-upload-artifact@v4/dist/upload/index.js] user= workdir=
[Playwright Tests/test]   🚧  ::warning::No files were found with the provided path: playwright-report/. No artifacts will be uploaded.
[Playwright Tests/test]   ✅  Success - Main actions/upload-artifact@v4 [989.559666ms]
[Playwright Tests/test] ⭐ Run Complete job
```

```yml
name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 8.0.4
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```
