### ISSUE TITLE
[Bug/Feature Request?]

### ISSUE THREAD

**Issue by DanMossa** [supercharge/mongodb-github-action#9]
Hello!

I'm currently using this github action with 

```
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: '4.2'
```

I'm also using mongoose and everything works great except that one part of my code sets the `ttlMonitorSleepSecs` in mongo and this works locally but I don't believe it's working via github actions

```
  const ttlMonitorSleepSecs = config.get('time').ttlMonitorSleepSecs;
    await mongoose.connect(database);
    logger.info('mongooseInitSuccess', `MongoDB database connection established successfully`);

    await mongoose.connection.db.admin().command({ setParameter: 1, ttlMonitorSleepSecs });
    await mongoose.connection.db.admin().command({ setParameter: 1, ttlMonitorEnabled: false });
    await mongoose.connection.db.admin().command({ setParameter: 1, ttlMonitorEnabled: true });

    logger.info('mongooseInitChangeTTL', `Successfully changed ttlMonitorSleepSecs to ${ttlMonitorSleepSecs}`);
```

In this case, `ttlMonitorSleepSecs` is set to 1 during sets. I'm not sure if I'm either not setting this up correctly or if this isn't a support feature at the moment?

Thanks!
